(()=>{
  const openBtn=document.getElementById('openBoggartGame'),teacher=document.getElementById('lupinCharacterButton'),modal=document.getElementById('boggartModal');
  if(!openBtn||!modal)return;
  const closeBtn=document.getElementById('boggartClose'),stage=document.getElementById('boggartStage'),startBtn=document.getElementById('boggartStart'),status=document.getElementById('boggartStatus'),comment=document.getElementById('lupinBoggartComment'),closed=document.getElementById('boggartWardrobeClosed'),opened=document.getElementById('boggartWardrobeOpen'),figure=document.getElementById('boggartFigure'),roundBadge=document.getElementById('boggartRoundBadge'),gestureBox=document.getElementById('boggartGestureBox'),choicesWrap=document.getElementById('boggartChoices'),canvas=document.getElementById('gestureCanvas'),ctx=canvas.getContext('2d');
  const rounds=[
    {name:'Mozkomor',fear:'img/boggart-dementor-v42.webp',fun:'img/boggart-clown-v42.webp',correct:'clown',options:[['clown','Udělám z něj potrhaného klauna'],['shadow','Ještě temnější plášť'],['chains','Těžké řetězy']],after:'„Výborně. Když je směšný, už není všemocný.“'},
    {name:'Kobra',fear:'img/boggart-cobra-v42.webp',fun:'img/boggart-devil-v42.webp',correct:'devil',options:[['crown','Ještě větší korunu'],['devil','Čertík v krabičce'],['fangs','Ještě delší tesáky']],after:'„Přesně. Strach se právě změnil v grotesku.“'},
    {name:'Přísný profesor',fear:'img/profesor-snape-v42.webp',fun:'img/boggart-snape-costume-v42.webp',correct:'costume',options:[['sword','Obrovský meč'],['costume','Zelený kostýmek, klobouk a kabelka'],['cloak','Ještě delší černý plášť']],after:'„Tohle už si zapamatuješ. Riddikulus!“'}
  ];
  let round=0,phase='idle',drawing=false,points=[],transitionTimer=null;
  function resizeCanvas(){const r=canvas.getBoundingClientRect(),d=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));ctx.setTransform(d,0,0,d,0,0);ctx.lineWidth=4;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#e0bf69'}
  function clearCanvas(){resizeCanvas();ctx.clearRect(0,0,canvas.width,canvas.height);points=[]}
  function setWardrobe(isOpen){stage.classList.toggle('is-open',isOpen);closed.hidden=isOpen;opened.hidden=!isOpen}
  function renderChoices(){const r=rounds[round];choicesWrap.innerHTML=r.options.map(([id,label])=>`<button type="button" data-choice="${id}">${label}</button>`).join('');choicesWrap.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>choose(b.dataset.choice,b)))}
  function resetRound(){clearTimeout(transitionTimer);phase='idle';stage.classList.remove('is-ridiculous','is-hiding');setWardrobe(false);gestureBox.hidden=true;choicesWrap.hidden=true;figure.hidden=true;figure.src='';roundBadge.textContent=`${round+1} / ${rounds.length}`;status.textContent='Skříň je zavřená.';comment.textContent=round===0?'„Bubák se živí strachem. Udělej z něj něco směšného a ztratí nad tebou moc.“':'„Další. Soustřeď se a nenech ho rozhodovat za tebe.“';startBtn.hidden=false;startBtn.textContent='Otevřít skříň'}
  function beginRound(){const r=rounds[round];phase='gesture';setWardrobe(true);figure.src=r.fear;figure.alt=r.name;figure.hidden=false;gestureBox.hidden=false;choicesWrap.hidden=true;renderChoices();clearCanvas();startBtn.hidden=true;status.textContent=`Ze skříně vystoupil ${r.name}. Nakresli široký oblouk hůlkou.`;comment.textContent='„Klid. Hůlku pevně. Soustřeď se na pohyb.“'}
  function pos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
  canvas.addEventListener('pointerdown',e=>{if(phase!=='gesture')return;drawing=true;points=[pos(e)];canvas.setPointerCapture?.(e.pointerId);ctx.beginPath();ctx.moveTo(points[0].x,points[0].y)});
  canvas.addEventListener('pointermove',e=>{if(!drawing||phase!=='gesture')return;const p=pos(e);points.push(p);ctx.lineTo(p.x,p.y);ctx.stroke()});
  canvas.addEventListener('pointerup',()=>{if(!drawing||phase!=='gesture')return;drawing=false;if(points.length<5){status.textContent='Pohyb byl příliš krátký. Zkus větší oblouk.';clearCanvas();return}let len=0,minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(let i=1;i<points.length;i++){len+=Math.hypot(points[i].x-points[i-1].x,points[i].y-points[i-1].y);minX=Math.min(minX,points[i].x);maxX=Math.max(maxX,points[i].x);minY=Math.min(minY,points[i].y);maxY=Math.max(maxY,points[i].y)}const r=canvas.getBoundingClientRect();const ok=len>r.width*.55&&(maxX-minX)>r.width*.42&&(maxY-minY)>r.height*.16;if(!ok){status.textContent='Ještě jednou — širší, jistější oblouk.';comment.textContent='„Neškrábej hůlkou vzduch. Veď ji.“';clearCanvas();return}phase='choice';gestureBox.hidden=true;choicesWrap.hidden=false;status.textContent='Teď vyber směšnou proměnu.';comment.textContent='„Teď! Ne děsivější. Směšnější.“'});
  function choose(id,button){if(phase!=='choice')return;const r=rounds[round];if(id!==r.correct){button.disabled=true;status.textContent='Tím by byl bubák jen děsivější. Zkus něco opravdu absurdního.';comment.textContent='„Ne. Cílem není strach posílit.“';return}phase='result';choicesWrap.hidden=true;stage.classList.add('is-ridiculous');figure.src=r.fun;figure.alt=`Směšná proměna: ${r.name}`;status.textContent='Riddikulus! Bubák ztrácí sílu.';comment.textContent=r.after;transitionTimer=setTimeout(async()=>{stage.classList.add('is-hiding');setWardrobe(false);figure.hidden=true;if(round<rounds.length-1){round++;setTimeout(resetRound,420);return}phase='done';roundBadge.textContent='3 / 3 ✓';status.textContent='Zkouška splněna. Všichni tři bubáci ustoupili.';comment.textContent='„Výborně. Strach se dá zvládnout, když nad ním převezmeš kontrolu.“';startBtn.hidden=false;startBtn.textContent='Zkusit znovu';let dbHandled=false;try{const pts=await window.BradaviceDB?.claimV42Activity?.('lupin-boggart',3);dbHandled=Number.isFinite(Number(pts))}catch(e){console.warn('Lupin v42 DB:',e)}window.BradaviceAchievements?.completeQuest?.('lupin-boggart',{points:dbHandled?0:20,badgeId:'obrance-hradu',title:'Lupinova praktická zkouška',syncDb:!dbHandled});startBtn.onclick=()=>{round=0;resetRound();startBtn.onclick=beginRound}},1350)}
  const show=()=>{round=0;modal.hidden=false;document.body.style.overflow='hidden';resetRound();startBtn.onclick=beginRound};
  function hide(){clearTimeout(transitionTimer);modal.hidden=true;document.body.style.overflow=''}
  openBtn.addEventListener('click',show);teacher?.addEventListener('click',show);closeBtn.addEventListener('click',hide);modal.addEventListener('click',e=>{if(e.target===modal)hide()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)hide()});window.addEventListener('resize',()=>{if(!modal.hidden&&!gestureBox.hidden)clearCanvas()});startBtn.onclick=beginRound;
})();
