(()=>{
  const KEY='bradavice_herbarium_v42',A=window.BradaviceAchievements,DB=window.BradaviceDB;
  const plantDefs={
    jmeli:{name:'Jmelí',src:'img/plant-jmeli-v423.webp'},salvej:{name:'Šalvěj',src:'img/plant-salvej-v423.webp'},kopriva:{name:'Kopřiva',src:'img/plant-kopriva-v423.webp'},brectan:{name:'Břečťan',src:'img/plant-brectan-v423.webp'},houby:{name:'Houby',src:'img/plant-houby-v423.webp'}
  };
  const blank=()=>({accepted:false,found:{jmeli:false,salvej:false,kopriva:false,brectan:false,houby:false},done:false,reward:0,best:0});
  const load=()=>{try{const raw=JSON.parse(localStorage.getItem(KEY)||'{}')||{};return{...blank(),...raw,found:{...blank().found,...(raw.found||{})}}}catch{return blank()}};
  const save=s=>localStorage.setItem(KEY,JSON.stringify(s));let state=load();
  function toast(text){let t=document.querySelector('.herb-toast');if(!t){t=document.createElement('div');t.className='herb-toast';document.body.appendChild(t)}t.textContent=text;t.classList.remove('show');void t.offsetWidth;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2600)}
  const page=location.pathname.split('/').pop();
  const placements={
    'jezero.html':[{id:'kopriva',cls:'plant-kopriva'}],
    'pozemky.html':[{id:'salvej',cls:'plant-salvej'}],
    'zapovezeny-les.html':[{id:'houby',cls:'plant-houby'},{id:'brectan',cls:'plant-brectan'},{id:'jmeli',cls:'plant-jmeli'}]
  };
  function mountPlants(){const specs=placements[page]||[];if(!specs.length)return;const host=document.querySelector('.place-scene')||document.querySelector('.willow')||document.querySelector('main');if(!host)return;specs.forEach(spec=>{const def=plantDefs[spec.id],b=document.createElement('button');b.type='button';b.className=`herb-specimen ${spec.cls}`;b.hidden=!state.accepted||state.done||state.found[spec.id];b.dataset.herbId=spec.id;b.setAttribute('aria-label',`Rostlina do herbáře`);b.innerHTML=`<img src="${def.src}" alt="${def.name}">`;host.appendChild(b);b.addEventListener('click',()=>{state=load();if(!state.accepted){toast('Nejdřív si promluv s profesorkou Prýtovou.');return}if(state.found[spec.id])return;state.found[spec.id]=true;save(state);b.classList.add('herb-found');const n=Object.values(state.found).filter(Boolean).length;toast(n===5?'Pátý vzorek nalezen. Vrať se do skleníku.':`Vzorek uložen do herbáře · ${n} / 5`);setTimeout(()=>b.hidden=true,650)})})}
  mountPlants();

  const professor=document.getElementById('prytovaTeacher')||document.querySelector('.prytova-character'),modal=document.getElementById('herbQuestModal');if(!professor||!modal)return;
  const close=document.getElementById('herbQuestClose'),dialog=document.getElementById('herbQuestDialog'),progress=document.getElementById('herbProgress'),mainAction=document.getElementById('herbMainAction'),transplant=document.getElementById('herbTransplant'),transStatus=document.getElementById('transplantStatus'),startBtn=document.getElementById('transplantStart'),steps=document.getElementById('transplantSteps'),timerEl=document.getElementById('transplantTimer'),countEl=document.getElementById('transplantCount'),instruction=document.getElementById('transplantInstruction'),workbench=document.querySelector('.mandrake-workbench');
  let timer=null,seconds=60,currentStep=0,transplanted=0,running=false;
  const foundCount=()=>Object.values(state.found||{}).filter(Boolean).length;
  function renderProgress(){const order=['jmeli','salvej','kopriva','brectan','houby'];progress.innerHTML=order.map((id,i)=>`<div class="${state.found[id]?'done':''}"><strong>${state.found[id]?plantDefs[id].name:`Vzorek ${i+1}`}</strong><span>${state.found[id]?'nalezeno ✓':'nenalezeno'}</span></div>`).join('')}
  function render(){state=load();renderProgress();if(state.done){dialog.innerHTML=`<strong>„Úkol splněn.“</strong> Nejlepší výkon: ${state.best||0} přesazených mandragor. Odměna byla ${state.reward||0} bodů pro kolej.`;mainAction.hidden=true;transplant.hidden=true;return}if(!state.accepted){dialog.textContent='„Přines mi pět různých rostlin z okolí školy. Kde rostou, to ti neprozradím — herbář není seznam nákupů. Až je najdeš, čeká tě práce s mandragorami.“';mainAction.hidden=false;mainAction.textContent='Přijmout úkol';transplant.hidden=true;return}const n=foundCount();if(n<5){dialog.textContent=`„Máš ${n} z 5 vzorků. Nedívej se jen doprostřed cesty. Rostliny obvykle rostou tam, kde jim to dává smysl.“`;mainAction.hidden=true;transplant.hidden=true;return}dialog.textContent='„Výborně. Herbář je kompletní. Teď si nasaď klapky a ukaž, kolik mandragor zvládneš správně přesadit za jednu minutu.“';mainAction.hidden=true;transplant.hidden=false;if(!running){countEl.textContent='0';timerEl.textContent='60';transStatus.textContent='Každá mandragora: vytáhnout → přesunout do květináče → zasypat. Chybný krok stojí 2 sekundy.'}}
  mainAction.addEventListener('click',()=>{state=load();state.accepted=true;save(state);render();toast('Úkol přijat · najdi 5 rostlin')});
  function resetGame(){clearInterval(timer);timer=null;seconds=60;currentStep=0;transplanted=0;running=false;workbench?.classList.remove('step-pulled','step-potted','step-done');timerEl.textContent='60';countEl.textContent='0';steps.hidden=true;startBtn.hidden=false;startBtn.disabled=false;instruction.textContent='Nasadíš chrániče sluchu a pak máš jednu minutu.';transStatus.textContent=''}
  function startGame(){if(running)return;running=true;seconds=60;currentStep=0;transplanted=0;workbench?.classList.remove('step-pulled','step-potted','step-done');timerEl.textContent=seconds;countEl.textContent='0';startBtn.hidden=true;steps.hidden=false;instruction.textContent='Klapky drží. Pracuj rychle, ale ve správném pořadí.';transStatus.textContent='První mandragora čeká.';timer=setInterval(()=>{seconds--;timerEl.textContent=Math.max(0,seconds);if(seconds<=0)finishGame()},1000)}
  startBtn.addEventListener('click',startGame);
  document.querySelectorAll('[data-transplant-action]').forEach((b,i)=>b.addEventListener('click',()=>{if(!running)return;const expected=['pull','pot','soil'][currentStep];if(b.dataset.transplantAction!==expected){seconds=Math.max(0,seconds-2);timerEl.textContent=seconds;transStatus.textContent='Špatný krok. Mandragora se vzpírá — ztrácíš 2 sekundy.';if(seconds<=0)finishGame();return}currentStep++;b.classList.remove('pulse');void b.offsetWidth;b.classList.add('pulse');if(currentStep===1){workbench?.classList.add('step-pulled')}if(currentStep===2){workbench?.classList.add('step-potted')}if(currentStep===3){workbench?.classList.add('step-done');currentStep=0;transplanted++;countEl.textContent=transplanted;transStatus.textContent=transplanted%5===0?`Už ${transplanted}. Profesorka jen uznale přikývla.`:'Další mandragora je bezpečně v květináči.';setTimeout(()=>workbench?.classList.remove('step-pulled','step-potted','step-done'),260)}}));
  function tier(n){if(n>=15)return{points:50,text:'„No, no, výborně! Letos se úroda opravdu vyvede. 50 bodů pro tvou kolej!“'};if(n>=10)return{points:20,text:'„To už je práce, která se dá pochválit. 20 bodů pro tvou kolej.“'};if(n>=5)return{points:5,text:'„No… alespoň za snahu. 5 bodů pro tvou kolej.“'};return{points:0,text:'„Ty sis nenasadil klapky, že jsi usnul? Tohle zkusíme ještě jednou.“'}}
  async function finishGame(){if(!running)return;running=false;clearInterval(timer);timer=null;steps.hidden=true;const t=tier(transplanted);instruction.textContent=`Čas vypršel · přesazeno ${transplanted} mandragor.`;transStatus.textContent=t.text;state=load();state.best=Math.max(Number(state.best||0),transplanted);save(state);if(t.points<=0){startBtn.hidden=false;startBtn.textContent='Zkusit znovu';return}let dbRewarded=false;try{if(DB?.client&&DB?.claimV42Activity){const pts=await DB.claimV42Activity('herbarium-prytova',transplanted);dbRewarded=Number.isFinite(Number(pts))}}catch(e){console.warn('Prýtová v42 DB:',e)}state=load();state.done=true;state.reward=t.points;state.best=Math.max(Number(state.best||0),transplanted);save(state);A?.completeQuest?.('herbarium-prytova',{points:dbRewarded?0:t.points,badgeId:'sklenikovy-znalec',title:'Profesorka Prýtová · Herbář a mandragory',syncDb:!dbRewarded});startBtn.hidden=true;setTimeout(render,1800)}
  professor.addEventListener('click',()=>{modal.hidden=false;document.body.style.overflow='hidden';render()});close.addEventListener('click',()=>{modal.hidden=true;document.body.style.overflow='';if(running)resetGame()});modal.addEventListener('click',e=>{if(e.target===modal){modal.hidden=true;document.body.style.overflow='';if(running)resetGame()}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden){modal.hidden=true;document.body.style.overflow='';if(running)resetGame()}});
})();
