(()=>{
  const open=document.getElementById('openPotionDuel'),modal=document.getElementById('potionDuelModal');
  if(!open||!modal)return;
  const close=document.getElementById('potionDuelClose'),createBtn=document.getElementById('potionDuelCreate'),joinBtn=document.getElementById('potionDuelJoin'),joinInput=document.getElementById('potionDuelCodeInput'),codeEl=document.getElementById('potionDuelRoomCode'),onlineStatus=document.getElementById('potionDuelOnlineStatus');
  const lobby=document.getElementById('potionDuelLobby'),play=document.getElementById('potionDuelPlay'),stageNote=document.getElementById('potionDuelStageNote'),memory=document.getElementById('potionDuelMemory'),game=document.getElementById('potionDuelGame'),outcome=document.getElementById('potionDuelOutcome');
  const recipeName=document.getElementById('potionDuelRecipeName'),recipeSteps=document.getElementById('potionDuelRecipeSteps'),timerEl=document.getElementById('potionDuelTimer'),shelf=document.getElementById('potionDuelShelf'),cauldron=document.getElementById('potionDuelCauldron'),stepCount=document.getElementById('potionDuelStepCount'),sequence=document.getElementById('potionDuelSequence'),brewStatus=document.getElementById('potionDuelBrewStatus'),opponentProgress=document.getElementById('potionDuelOpponentProgress');
  const myName=document.getElementById('potionDuelMyName'),opName=document.getElementById('potionDuelOpponentName'),scoreEl=document.getElementById('potionDuelScore'),roundEl=document.getElementById('potionDuelRound'),outcomeTitle=document.getElementById('potionDuelOutcomeTitle'),outcomeText=document.getElementById('potionDuelOutcomeText');
  const DB=window.BradaviceDB;
  const ING={
    mandragora:['Mandragora','mandragora.webp'],kridla:['Křídla víly','kridla-vily.webp'],kridlaHmyzu:['Křídla hmyzu','kridla-hmyzu.webp'],pelynek:['Pelyněk','pelynek.webp'],bezoar:['Bezoár','bezoar.webp'],omej:['Oměj','omej.webp'],asfodel:['Kořen asfodelu','asfodelovy-koren.webp'],fazolky:['Fazolky','fazolky.webp'],belladonna:['Belladonna','belladonna.webp'],kozlik:['Kořen kozlíku','koren-kozlika.webp'],pijavice:['Pijavice','pijavice.webp'],mesicni:['Měsíční prášek','mesicni-prasek.webp'],hadi:['Hadí kůže','hadi-kuze.webp'],krvavy:['Krvavý extrakt','krvavy-extrakt.webp'],sliz:['Magický sliz','sliz.webp'],kostni:['Kostní prášek','kostni-prasek.webp'],roh:['Drcený roh','roh.webp'],semena:['Stříbrná semena','semena-stribrne.webp'],listy:['Sušené listy','susene-listy.webp'],plod:['Sušený plod','suseny-plod.webp']
  };
  const RECIPES=[
    {id:'uklidnujici',name:'Uklidňující odvar',steps:[['i','fazolky'],['i','fazolky'],['r'],['r'],['i','pelynek'],['h'],['i','bezoar'],['f']]},
    {id:'mnoholicny',name:'Mnoholičný lektvar',steps:[['i','hadi'],['i','pijavice'],['r'],['r'],['i','sliz'],['i','mandragora'],['l'],['h'],['f']]},
    {id:'probuzeni',name:'Lektvar probuzení',steps:[['i','kozlik'],['i','mesicni'],['l'],['l'],['i','kridlaHmyzu'],['h'],['r'],['f']]},
    {id:'peprovy',name:'Pepřový lektvar',steps:[['i','plod'],['i','plod'],['r'],['r'],['r'],['i','listy'],['h'],['f']]},
    {id:'zapomneni',name:'Lektvar zapomnění',steps:[['i','belladonna'],['i','asfodel'],['l'],['l'],['i','mesicni'],['l'],['h'],['f']]},
    {id:'pravdomluvnost',name:'Lektvar pravdomluvnosti',steps:[['i','semena'],['i','mesicni'],['r'],['i','kozlik'],['r'],['i','kridla'],['h'],['f']]},
    {id:'sila',name:'Lektvar síly',steps:[['i','roh'],['i','kostni'],['i','mandragora'],['r'],['r'],['r'],['h'],['f']]},
    {id:'spanek',name:'Spánkový lektvar',steps:[['i','asfodel'],['i','pelynek'],['i','kozlik'],['l'],['l'],['l'],['h'],['f']]},
    {id:'stesti',name:'Lektvar štěstí',steps:[['i','kridla'],['i','semena'],['i','mesicni'],['r'],['l'],['r'],['h'],['f']]},
    {id:'protijed',name:'Protijed',steps:[['i','bezoar'],['i','listy'],['i','belladonna'],['l'],['r'],['i','omej'],['h'],['f']]},
    {id:'jasna-mysl',name:'Lektvar jasné mysli',steps:[['i','mesicni'],['i','semena'],['l'],['i','kozlik'],['r'],['r'],['i','asfodel'],['h'],['f']]},
    {id:'obnova',name:'Obnovující tonikum',steps:[['i','listy'],['i','kozlik'],['i','kozlik'],['r'],['i','bezoar'],['l'],['h'],['f']]},
    {id:'soustredeni',name:'Elixír soustředění',steps:[['i','pelynek'],['i','mesicni'],['r'],['l'],['r'],['i','semena'],['i','kridlaHmyzu'],['h'],['f']]},
    {id:'odvaha',name:'Lektvar odvahy',steps:[['i','roh'],['i','fazolky'],['r'],['r'],['i','krvavy'],['l'],['i','mandragora'],['h'],['f']]},
    {id:'stribrny-tonik',name:'Stříbrný tonik',steps:[['i','semena'],['i','semena'],['l'],['i','kridla'],['r'],['i','bezoar'],['r'],['h'],['f']]}
  ];
  const byId=Object.fromEntries(RECIPES.map(r=>[r.id,r]));
  const labels={r:'Zamíchat doprava',l:'Zamíchat doleva',h:'Zahřát kotlík',f:'Dokončit lektvar'};
  const actionKey=(type,id)=>type==='i'?`i:${id}`:type,stepKey=s=>s[0]==='i'?`i:${s[1]}`:s[0],stepLabel=s=>s[0]==='i'?`Přidat: ${ING[s[1]][0]}`:labels[s[0]];
  const clone=v=>JSON.parse(JSON.stringify(v||{}));
  const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
  function makeDuelState(){
    const chosen=shuffle(RECIPES).slice(0,3);
    const shelves=chosen.map(recipe=>{const used=[...new Set(recipe.steps.filter(s=>s[0]==='i').map(s=>s[1]))];const extras=shuffle(Object.keys(ING).filter(x=>!used.includes(x))).slice(0,Math.max(4,10-used.length));return shuffle([...used,...extras])});
    return {kind:'potion-duel-v1',recipes:chosen.map(r=>r.id),shelves,round:0,phase:'waiting',phaseStartedAt:0,scores:{h:0,g:0},results:{},roundWinner:null,lastRound:null,ended:false,winner:null};
  }
  let online={code:'',seat:null,version:0,ready:false,channel:null,poll:null,leaving:false,hostName:'',guestName:''};
  let roomState=null,phaseToken='',timer=null,recipe=null,index=0,errors=0,history=[],brewing=false,submitted=false,brewStartedAt=0,opponent={index:0,total:0,errors:0,done:false};
  const mySeat=()=>online.seat,otherSeat=()=>online.seat==='h'?'g':'h';
  function say(t){onlineStatus.textContent=t||''}
  function clearTimer(){if(timer){clearInterval(timer);timer=null}}
  function setControls(v){shelf.querySelectorAll('button').forEach(b=>b.disabled=v);document.querySelectorAll('[data-duel-brew-action]').forEach(b=>b.disabled=v)}
  function pulse(){cauldron.classList.add('active');setTimeout(()=>cauldron.classList.remove('active'),500)}
  function namesFromRoom(r){online.hostName=r.host_name||'Student';online.guestName=r.guest_name||'Soupeř';myName.textContent=online.seat==='h'?online.hostName:online.guestName;opName.textContent=online.seat==='h'?online.guestName:online.hostName}
  function scoreText(state){const s=state?.scores||{h:0,g:0};const mine=Number(s[mySeat()]||0),theirs=Number(s[otherSeat()]||0);scoreEl.textContent=`${mine} : ${theirs}`;roundEl.textContent=state?.ended?'Konec duelu':`Kolo ${Number(state?.round||0)+1} / 3`}
  function roomSummary(r){online.version=Number(r.version||0);online.ready=r.status==='playing'||r.status==='ended';if(codeEl)codeEl.textContent=r.room_code||online.code;namesFromRoom(r);if(r.status==='waiting')say(`Kód ${r.room_code}. Pošli ho spolužákovi a počkej na připojení.`);else if(r.status==='playing')say(`${r.host_name||'Student'} × ${r.guest_name||'Soupeř'} · duel o nejlepšího lektvaristu`);else if(r.status==='abandoned'){online.ready=false;say('Soupeř duel opustil.');showAbandoned()}else if(r.status==='ended')say('Duel skončil.')}
  async function removeChannel(){if(online.poll){clearInterval(online.poll);online.poll=null}if(online.channel&&DB?.client){try{await DB.client.removeChannel(online.channel)}catch{}online.channel=null}}
  async function leave({notify=true}={}){if(online.leaving)return;online.leaving=true;const code=online.code;clearTimer();await removeChannel();if(notify&&code)try{await DB?.leavePotionDuelRoom?.(code)}catch{}online={code:'',seat:null,version:0,ready:false,channel:null,poll:null,leaving:false,hostName:'',guestName:''};roomState=null;phaseToken='';}
  async function refresh(code,{force=false}={}){if(!online.code||online.code!==code)return;try{const r=await DB?.getPotionDuelRoom?.(code);if(!r)return;const changed=force||Number(r.version||0)>online.version||r.status==='abandoned';if(!changed)return;roomSummary(r);applyRoom(r)}catch(e){console.warn('Lektvarový duel synchronizace:',e)}}
  async function subscribe(code){await removeChannel();if(DB?.client){try{const ch=DB.client.channel(`v435-potion-duel-${code}`);ch.on('postgres_changes',{event:'*',schema:'public',table:'potion_duel_rooms',filter:`room_code=eq.${code}`},()=>refresh(code,{force:true}));ch.on('broadcast',{event:'potion-progress'},({payload})=>{if(!payload||payload.seat===online.seat||Number(payload.round)!==Number(roomState?.round))return;opponent={index:Number(payload.index||0),total:Number(payload.total||0),errors:Number(payload.errors||0),done:Boolean(payload.done)};renderOpponent()});ch.subscribe();online.channel=ch}catch(e){console.warn('Lektvarový duel realtime:',e)}}online.poll=setInterval(()=>refresh(code),1500)}
  function broadcastProgress(done=false){try{online.channel?.send({type:'broadcast',event:'potion-progress',payload:{seat:online.seat,round:roomState?.round,index,total:recipe?.steps?.length||0,errors,done}})}catch{}}
  async function updateFresh(mutator,tries=4){let lastErr;for(let n=0;n<tries;n++){try{const fresh=await DB.getPotionDuelRoom(online.code);const st=clone(fresh.state);const next=mutator(st,fresh);if(!next)return fresh;const r=await DB.updatePotionDuelRoom(online.code,next,Number(fresh.version||0));roomSummary(r);applyRoom(r);return r}catch(e){lastErr=e;await new Promise(res=>setTimeout(res,120+80*n))}}throw lastErr||new Error('Duel se nepodařilo synchronizovat.')}
  async function createRoom(){if(!DB?.client||!DB?.createPotionDuelRoom){say('Pro duel je potřeba databázový update v43.5.7.');return}await leave();online.seat='h';lobby.hidden=false;play.hidden=true;say('Zakládám duel…');try{const r=await DB.createPotionDuelRoom(makeDuelState());online.code=r.room_code;online.version=Number(r.version||0);roomSummary(r);applyRoom(r);await subscribe(online.code);await refresh(online.code,{force:true})}catch(e){say(e?.message||'Duel se nepodařilo vytvořit.')}}
  async function joinRoom(){const code=String(joinInput.value||'').trim().toUpperCase();if(code.length!==6){say('Zadej šestimístný kód duelu.');return}if(!DB?.joinPotionDuelRoom){say('Pro duel je potřeba databázový update v43.5.7.');return}await leave();online.seat='g';say('Připojuji se…');try{const r=await DB.joinPotionDuelRoom(code);online.code=r.room_code;online.version=Number(r.version||0);roomSummary(r);applyRoom(r);await subscribe(online.code);await refresh(online.code,{force:true})}catch(e){say(e?.message||'K duelu se nepodařilo připojit.')}}
  function applyRoom(r){roomState=clone(r.state||{});scoreText(roomState);if(r.status==='waiting'){lobby.hidden=false;play.hidden=true;return}lobby.hidden=true;play.hidden=false;if(r.status==='abandoned'){showAbandoned();return}const token=`${roomState.round}:${roomState.phase}:${roomState.phaseStartedAt||0}:${roomState.ended?'1':'0'}`;if(token===phaseToken){if(online.seat==='h'&&roomState.phase==='brewing')maybeResolve();return}phaseToken=token;clearTimer();opponent={index:0,total:byId[roomState.recipes?.[roomState.round]]?.steps?.length||0,errors:0,done:false};renderOpponent();if(roomState.ended||roomState.phase==='ended'){renderFinal();return}if(roomState.phase==='waiting'){if(online.seat==='h'&&online.ready)startRoundMemory();else renderWaiting('Čekáme na zahájení prvního kola.');return}if(roomState.phase==='memory'){renderMemoryPhase();return}if(roomState.phase==='brewing'){renderBrewPhase();if(online.seat==='h')maybeResolve();return}if(roomState.phase==='round-result'){renderRoundResult();if(online.seat==='h')scheduleNextRound();return}}
  function renderWaiting(text){memory.hidden=true;game.hidden=true;outcome.hidden=true;stageNote.hidden=false;stageNote.innerHTML=`<span>${text}</span>`}
  async function startRoundMemory(){if(!online.code)return;try{await updateFresh(st=>{if(st.phase!=='waiting'&&st.phase!=='round-result')return null;st.phase='memory';st.phaseStartedAt=Date.now()+2200;st.roundWinner=null;st.lastRound=null;return st})}catch(e){console.warn(e)}}
  function currentRecipe(){return byId[roomState?.recipes?.[roomState?.round]]||RECIPES[0]}
  function renderMemoryPhase(){submitted=false;brewing=false;index=0;errors=0;history=[];recipe=currentRecipe();setControls(true);sequence.textContent='Zatím žádný krok.';stepCount.textContent=`0 / ${recipe.steps.length}`;brewStatus.textContent='';recipeName.textContent=recipe.name;const grouped=[];for(const st of recipe.steps){const k=stepKey(st),prev=grouped[grouped.length-1];if(prev&&prev.key===k)prev.count++;else grouped.push({key:k,step:st,count:1})}recipeSteps.innerHTML=grouped.map(x=>`<li>${x.count>1?`${x.count}× `:''}${stepLabel(x.step)}</li>`).join('');buildShelf();memory.hidden=true;game.hidden=true;outcome.hidden=true;stageNote.hidden=false;const startAt=Number(roomState.phaseStartedAt||Date.now());const tick=()=>{const now=Date.now();if(now<startAt){stageNote.innerHTML=`Kolo začne za <strong class="duel-waiting-countdown">${Math.max(1,Math.ceil((startAt-now)/1000))}</strong>`;timerEl.textContent='20';return}stageNote.hidden=true;memory.hidden=false;const left=Math.max(0,20-Math.floor((now-startAt)/1000));timerEl.textContent=String(left);if(left<=0){clearTimer();renderBrewPhase()}};tick();timer=setInterval(tick,250)}
  function buildShelf(){const ids=roomState?.shelves?.[roomState.round]||[];shelf.innerHTML=ids.map(id=>`<button class="ingredient-card" type="button" data-duel-ingredient="${id}"><img src="img/potions-v40/ingredients/${ING[id][1]}" alt="${ING[id][0]}"><span>${ING[id][0]}</span></button>`).join('');shelf.querySelectorAll('[data-duel-ingredient]').forEach(b=>b.addEventListener('click',()=>act('i',b.dataset.duelIngredient)))}
  function renderBrewPhase(){recipe=currentRecipe();memory.hidden=true;outcome.hidden=true;stageNote.hidden=true;game.hidden=false;if(!brewing){brewing=true;submitted=false;index=0;errors=0;history=[];brewStartedAt=Number(roomState.phaseStartedAt||Date.now())+20000;sequence.textContent='Zatím žádný krok.';stepCount.textContent=`0 / ${recipe.steps.length}`;brewStatus.textContent='Vař přesně. Chybný krok přidá chybu, ale můžeš pokračovat.';buildShelf();setControls(false)}const tick=()=>{const elapsed=Math.max(0,Date.now()-brewStartedAt);timerEl.textContent=String(Math.floor(elapsed/1000));if(elapsed>=90000&&!submitted){clearTimer();submitResult({complete:false,errors:errors+99,ms:90000,progress:index,total:recipe.steps.length})}};tick();timer=setInterval(tick,250)}
  function act(type,id=''){if(!brewing||submitted||!recipe)return;const got=actionKey(type,id),expected=stepKey(recipe.steps[index]);history.push(type==='i'?ING[id][0]:labels[type]);sequence.textContent=history.join(' → ');pulse();if(got!==expected){errors++;brewStatus.innerHTML=`Chyba <strong class="duel-errors">${errors}</strong> · správný krok musíš zkusit znovu.`;broadcastProgress(false);return}index++;stepCount.textContent=`${index} / ${recipe.steps.length}`;brewStatus.innerHTML=`Správně · chyby: <strong class="duel-errors">${errors}</strong>`;broadcastProgress(false);if(index>=recipe.steps.length)submitResult({complete:true,errors,ms:Math.max(1,Date.now()-brewStartedAt),progress:index,total:recipe.steps.length})}
  async function submitResult(res){if(submitted)return;submitted=true;setControls(true);clearTimer();broadcastProgress(true);brewStatus.textContent='Hotovo. Čekám na soupeře…';try{await updateFresh(st=>{if(st.phase!=='brewing'||Number(st.round)!==Number(roomState.round))return null;st.results=st.results||{};const key=String(st.round);st.results[key]=st.results[key]||{};st.results[key][online.seat]={...res,submittedAt:Date.now()};return st});if(online.seat==='h')maybeResolve()}catch(e){submitted=false;setControls(false);brewStatus.textContent='Výsledek se nepodařilo uložit. Zkus poslední krok znovu.';console.warn(e)}}
  function renderOpponent(){if(!recipe){opponentProgress.textContent='Soupeř: čeká se…';return}const done=opponent.done?' · hotovo':'';opponentProgress.textContent=`Soupeř: ${opponent.index}/${opponent.total||recipe.steps.length} kroků · ${opponent.errors} chyb${done}`}
  function compare(a,b){if(Boolean(a.complete)!==Boolean(b.complete))return a.complete?'h':'g';if(Number(a.errors)!==Number(b.errors))return Number(a.errors)<Number(b.errors)?'h':'g';if(!a.complete&&Number(a.progress)!==Number(b.progress))return Number(a.progress)>Number(b.progress)?'h':'g';if(Number(a.ms)!==Number(b.ms))return Number(a.ms)<Number(b.ms)?'h':'g';return 'draw'}
  async function maybeResolve(){if(online.seat!=='h'||!roomState||roomState.phase!=='brewing')return;const rr=roomState.results?.[String(roomState.round)]||{};if(!rr.h||!rr.g)return;try{await updateFresh(st=>{if(st.phase!=='brewing')return null;const pair=st.results?.[String(st.round)]||{};if(!pair.h||!pair.g)return null;const winner=compare(pair.h,pair.g),scores={h:Number(st.scores?.h||0),g:Number(st.scores?.g||0)};if(winner==='h'||winner==='g')scores[winner]++;st.scores=scores;st.roundWinner=winner;st.lastRound={round:st.round,h:pair.h,g:pair.g,winner};const duelDone=scores.h>=2||scores.g>=2||Number(st.round)>=2;if(duelDone){st.ended=true;st.phase='ended';st.winner=scores.h===scores.g?'draw':scores.h>scores.g?'h':'g'}else{st.phase='round-result';st.phaseStartedAt=Date.now();}return st})}catch(e){console.warn('Vyhodnocení kola:',e)}}
  function fmtResult(r){if(!r)return 'čeká se';if(!r.complete)return `nedokončeno · ${r.progress||0}/${r.total||0} kroků`;const sec=(Number(r.ms||0)/1000).toFixed(1).replace('.',',');return Number(r.errors||0)===0?`správně · ${sec} s`:`${r.errors} ${Number(r.errors)===1?'chyba':'chyby'} · ${sec} s`}
  function renderRoundResult(){memory.hidden=true;game.hidden=true;stageNote.hidden=true;outcome.hidden=false;const last=roomState.lastRound,seat=online.seat,winner=last?.winner;outcomeTitle.textContent=winner==='draw'?'Kolo skončilo remízou':winner===seat?'Vyhráváš kolo':'Kolo vyhrál soupeř';outcomeTitle.className=winner===seat?'duel-win':winner==='draw'?'':'duel-loss';outcomeText.innerHTML=`Ty: <strong>${fmtResult(last?.[seat])}</strong><br>Soupeř: <strong>${fmtResult(last?.[otherSeat()])}</strong><br><br>Další kolo začne za chvíli.`}
  function scheduleNextRound(){const start=Number(roomState.phaseStartedAt||Date.now());const delay=Math.max(0,start+5000-Date.now());clearTimer();timer=setTimeout(async()=>{try{await updateFresh(st=>{if(st.phase!=='round-result')return null;st.round=Number(st.round||0)+1;st.phase='memory';st.phaseStartedAt=Date.now()+2200;st.roundWinner=null;st.lastRound=null;return st})}catch(e){console.warn(e)}},delay)}
  function renderFinal(){memory.hidden=true;game.hidden=true;stageNote.hidden=true;outcome.hidden=false;const mine=Number(roomState.scores?.[mySeat()]||0),theirs=Number(roomState.scores?.[otherSeat()]||0),winner=roomState.winner;outcomeTitle.textContent=winner==='draw'?'Duel končí remízou':winner===online.seat?'VYHRÁVÁŠ DUEL':'DUEL PROHRÁVÁŠ';outcomeTitle.className=winner===online.seat?'duel-win':winner==='draw'?'':'duel-loss';outcomeText.innerHTML=`<div class="duel-final-score">${mine} : ${theirs}</div>${winner===online.seat?'Přesnější a rychlejší práce u kotlíku rozhodla.':winner==='draw'?'Po třech kolech jste vyrovnaní.':'Soupeř byl tentokrát přesnější nebo rychlejší.'}`}
  function showAbandoned(){lobby.hidden=true;play.hidden=false;memory.hidden=true;game.hidden=true;stageNote.hidden=true;outcome.hidden=false;outcomeTitle.textContent='Duel ukončen';outcomeText.textContent='Soupeř opustil místnost.'}
  function openModal(){modal.hidden=false;document.body.style.overflow='hidden';lobby.hidden=false;play.hidden=true;codeEl.textContent='—';say('Vytvoř soukromý duel nebo zadej kód spolužáka.')}
  async function shut(){await leave();modal.hidden=true;document.body.style.overflow=''}
  createBtn.addEventListener('click',createRoom);joinBtn.addEventListener('click',joinRoom);joinInput.addEventListener('input',()=>joinInput.value=joinInput.value.toUpperCase().replace(/[^A-F0-9]/g,'').slice(0,6));open.addEventListener('click',openModal);close.addEventListener('click',shut);modal.addEventListener('click',e=>{if(e.target===modal)shut()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)shut()});document.querySelectorAll('[data-duel-brew-action]').forEach(b=>b.addEventListener('click',()=>{const m={'stir-right':'r','stir-left':'l',heat:'h',finish:'f'};act(m[b.dataset.duelBrewAction])}));window.addEventListener('pagehide',()=>removeChannel().catch(()=>{}));
})();
