(() => {
  const Q=(q,correct,...wrong)=>({q,answers:[correct,...wrong],correct});
  const banks={
    potions:{title:'Lektvary',questions:[
      Q('Kdo vyučoval lektvary během prvních pěti let Harryho studia?','Severus Snape','Horacio Křiklan','Minerva McGonagallová','Filius Kratiknot'),
      Q('Jaký účinek má Felix Felicis?','Dočasně přináší mimořádné štěstí','Nutí člověka mluvit pravdu','Umožní dýchat pod vodou','Vyvolá hluboký spánek'),
      Q('K čemu slouží Veritaserum?','Nutí vypitého říkat pravdu','Mění vzhled člověka','Léčí většinu jedů','Zvyšuje kouzelnickou sílu'),
      Q('Co je Amortentia?','Mimořádně silný nápoj lásky','Protijed','Lektvar neviditelnosti','Lék na dračí neštovice'),
      Q('K čemu slouží Mnoholičný lektvar?','Dočasně změní vzhled člověka na jinou osobu','Promění člověka ve zvíře podle jeho volby','Umožní číst myšlenky','Způsobí zapomnění'),
      Q('Co způsobilo Hermioninu nepovedenou proměnu po Mnoholičném lektvaru?','Použila kočičí chlup','Zapomněla přidat pijavice','Přidala dračí krev','Vařila lektvar příliš krátce'),
      Q('Kde se přirozeně nachází bezoár?','V žaludku kozy','V dračím vejci','V kořeni mandragory','V rohu jednorožce'),
      Q('K čemu se bezoár používá?','Jako protijed proti mnoha jedům','Jako přísada do lektvaru lásky','K přeměně kovu ve zlato','K vyvolání snů'),
      Q('Co je Doušek živé smrti?','Velmi silný uspávací lektvar','Lektvar štěstí','Protijed proti baziliščímu jedu','Nápoj pravdy'),
      Q('Jaký lektvar Harry výborně uvařil na první hodině u Křiklana?','Doušek živé smrti','Mnoholičný lektvar','Felix Felicis','Vlkodlačí lektvar'),
      Q('Komu původně patřila učebnice označená jako majetek Prince dvojí krve?','Severusi Snapeovi','Jamesi Potterovi','Albusu Brumbálovi','Horaciu Křiklanovi'),
      Q('Jaký osobní prvek se přidává do Mnoholičného lektvaru těsně před použitím?','Část osoby, na kterou se chce pijící proměnit, například vlas','Kapka vlastní krve','Kousek vlastní hůlky','Popel z fénixe'),
      Q('Kdo připravoval Vlkodlačí lektvar pro Remuse Lupina během jeho působení v Bradavicích?','Severus Snape','Pomona Prýtová','Poppy Pomfreyová','Filius Kratiknot'),
      Q('Co Vlkodlačí lektvar Lupinovi umožňoval?','Zachovat si během proměny lidskou mysl','Zcela zabránit proměně','Proměnit se kdykoli dobrovolně','Vyléčit se z lykantropie'),
      Q('Co přípravek Kostirost dělá?','Nechá znovu dorůst chybějící kosti','Zpevní kouzelnickou hůlku','Léčí popáleniny','Zastaví účinek Mnoholičného lektvaru'),
      Q('Proč Harry potřeboval Kostirost ve druhém ročníku?','Lockhart mu odstranil kosti z ruky','Zlomil si obě nohy při pádu ze schodů','Pokousal ho bazilišek','Zasáhl ho potlouk do hrudi'),
      Q('Kdo byl profesorem lektvarů, když se Harry učil v šestém ročníku?','Horacio Křiklan','Severus Snape','Dolores Umbridgeová','Alastor Moody'),
      Q('Jakou cenu Křiklan nabídl za nejlepší Doušek živé smrti?','Malou lahvičku Felix Felicis','Lahvičku Veritasera','Bezoár','Mnoholičný lektvar'),
      Q('K čemu slouží Uklidňující lektvar?','Uklidňuje úzkost a rozrušení','Mění hlas','Zrychluje běh','Vyvolává vzpomínky'),
      Q('Co Snape v první hodině označil za jednu z možností lektvarů?','Uvařit slávu, stáčet úspěch a zastavit smrt','Vyčarovat jídlo z ničeho','Vrátit mrtvé k životu','Proměnit mudlu v kouzelníka')
    ]},
    transfiguration:{title:'Přeměňování',questions:[
      Q('Kdo vyučoval přeměňování během většiny Harryho studia?','Minerva McGonagallová','Pomona Prýtová','Sybilla Trelawneyová','Rolanda Hoochová'),
      Q('Do jakého zvířete se dokáže proměnit profesorka McGonagallová?','Do kočky','Do sovy','Do lišky','Do jelena'),
      Q('Co měli prváci na jedné z prvních hodin přeměňování změnit v jehlu?','Zápalku','Brk','Knoflík','Lžíci'),
      Q('Co McGonagallová před prváky proměnila v prase?','Svůj stůl','Katedru','Školní brašnu','Klec'),
      Q('Který student udělal při první proměně zápalky největší pokrok?','Hermiona Grangerová','Ron Weasley','Neville Longbottom','Draco Malfoy'),
      Q('Jakou zvěromágskou podobu má Sirius Black?','Velký černý pes','Jelen','Krysa','Vlk'),
      Q('Jakou zvěromágskou podobu měl James Potter?','Jelen','Pes','Kocour','Havran'),
      Q('Jakou zvěromágskou podobu měl Peter Pettigrew?','Krysa','Lasice','Kočka','Jezevec'),
      Q('Jakou zvěromágskou podobu používala Rita Holoubková?','Brouk','Moucha','Sova','Kočka'),
      Q('Kdo z této čtveřice byl registrovaným zvěromágem?','Minerva McGonagallová','Sirius Black','James Potter','Peter Pettigrew'),
      Q('Co je zvěromág?','Čaroděj, který se naučil měnit v určité zvíře','Čaroděj narozený s dračí krví','Kouzelný tvor schopný mluvit','Čaroděj ovládající pouze zvířecí kouzla'),
      Q('Kdo proměnil Draca Malfoye ve fretku?','Barty Skrk mladší vydávající se za Moodyho','Minerva McGonagallová','Severus Snape','Remus Lupin'),
      Q('Jaké kouzlo se používá k mizení předmětů?','Evanesco','Expelliarmus','Alohomora','Riddikulus'),
      Q('Co podle jedné z hlavních výjimek Gampova zákona nelze jednoduše vytvořit z ničeho?','Jídlo','Oheň','Vodu','Kouř'),
      Q('Kdo je metamorfomág?','Člověk schopný přirozeně měnit svůj vzhled','Zvěromág proměňující se jen za úplňku','Čaroděj ovládající Mnoholičný lektvar','Duch schopný měnit podobu'),
      Q('Která postava je známá jako metamorfomág?','Nymfadora Tonksová','Hermiona Grangerová','Luna Lovegoodová','Ginny Weasleyová'),
      Q('Je vlkodlak totéž co zvěromág?','Ne','Ano','Pouze za úplňku','Pouze pokud je registrovaný'),
      Q('Co je pro zvěromága charakteristické?','Má jednu konkrétní zvířecí podobu','Může se měnit v libovolné zvíře každou hodinu','Musí používat Mnoholičný lektvar','Proměňuje se jen při úplňku'),
      Q('Který úřad vede registr zvěromágů?','Ministerstvo kouzel','Gringottova banka','Bradavice','Denní věštec'),
      Q('Která disciplína patří k pokročilejším částem přeměňování?','Mizení','Vaření lektvarů','Věštění z čajových lístků','Péče o hipogryfy')
    ]},
    defense:{title:'Obrana proti černé magii',questions:[
      Q('Kdo učil Obranu proti černé magii v Harryho prvním ročníku?','Quirinus Quirrell','Severus Snape','Gilderoy Lockhart','Remus Lupin'),
      Q('Jaké zaklínadlo se používá proti bubákovi?','Riddikulus','Expelliarmus','Lumos','Alohomora'),
      Q('Jakou podobu na sebe bubák bere?','Toho, čeho se člověk nejvíc bojí','Nejbližšího přítele','Posledního seslaného kouzla','Vždy mozkomora'),
      Q('Jaká magie je nejúčinnější proti mozkomorům?','Patronovo zaklínadlo','Kletba Cruciatus','Mnoholičný lektvar','Petrificus Totalus'),
      Q('Jak zní zaklínadlo pro vyvolání patrona?','Expecto Patronum','Protego Maxima','Finite Incantatem','Wingardium Leviosa'),
      Q('Jakou podobu má Harryho patron?','Jelen','Vydra','Pes','Fénix'),
      Q('Co je Remus Lupin?','Vlkodlak','Zvěromág','Upír','Duch'),
      Q('Co dělá Expelliarmus?','Odzbrojí protivníka','Odemkne dveře','Zhasne světlo','Zmrazí vodu'),
      Q('K čemu slouží Protego?','Vytváří ochranný štít','Přivolává předmět','Mění vzpomínky','Léčí rány'),
      Q('Která z těchto kleteb patří mezi tři neprominutelné?','Imperius','Alohomora','Lumos','Reparo'),
      Q('Co způsobuje kletba Imperius?','Ovládne vůli oběti','Způsobí nesnesitelnou bolest','Okamžitě zabije','Vymaže paměť'),
      Q('Co způsobuje kletba Cruciatus?','Nesnesitelnou bolest','Spánek','Ztrátu hlasu','Proměnu ve zvíře'),
      Q('Jaký účinek má Avada Kedavra?','Usmrcení oběti','Odzbrojení','Petrifikaci','Ztrátu paměti'),
      Q('Co se stane při přímém pohledu do očí baziliška?','Oběť zemře','Oběť usne','Oběť oslepne na hodinu','Nestane se nic'),
      Q('Co se může stát při nepřímém pohledu na baziliška například přes odraz?','Petrifikace','Okamžitá smrt','Proměna v kámen navždy','Ztráta kouzelnické moci'),
      Q('Jaké tvory vypustil Lockhart ve své učebně?','Cornwallské rarachy','Skřítky Gringottovy banky','Mandragory','Testrály'),
      Q('Kdo učil Obranu proti černé magii ve třetím ročníku?','Remus Lupin','Gilderoy Lockhart','Dolores Umbridgeová','Severus Snape'),
      Q('Kdo se ve čtvrtém ročníku vydával za Alastora Moodyho?','Barty Skrk mladší','Lucius Malfoy','Peter Pettigrew','Igor Karkarov'),
      Q('Kdo učil Obranu proti černé magii v pátém ročníku?','Dolores Umbridgeová','Minerva McGonagallová','Horacio Křiklan','Filius Kratiknot'),
      Q('Kdo se stal profesorem Obrany proti černé magii v šestém ročníku?','Severus Snape','Remus Lupin','Alastor Moody','Rubeus Hagrid')
    ]},
    herbology:{title:'Bylinkářství',questions:[
      Q('Kdo vyučoval bylinkářství během Harryho studia?','Pomona Prýtová','Minerva McGonagallová','Sybilla Trelawneyová','Poppy Pomfreyová'),
      Q('Kterou kolej vedla profesorka Prýtová?','Mrzimor','Nebelvír','Havraspár','Zmijozel'),
      Q('Proč je křik dospělé mandragory nebezpečný?','Může člověka zabít','Vyvolává zapomnění','Promění člověka v kámen','Přivolá mozkomory'),
      Q('Co studenti používají při přesazování mandragor?','Chrániče sluchu','Ochranné brýle','Dračí rukavice jen na jednu ruku','Masku proti jedu'),
      Q('Co může způsobit křik mladé mandragory?','Bezvědomí na několik hodin','Trvalou hluchotu','Proměnu ve zvíře','Okamžitou smrt stejně jako dospělá'),
      Q('K čemu byl použit Mandragorový léčivý nápoj ve druhém ročníku?','K obnovení zkamenělých obětí','K léčbě vlkodlaků','K probuzení duchů','K odstranění kletby Imperius'),
      Q('Co Ďáblovo osidlo nemá rádo?','Světlo a teplo','Tmu a vlhko','Studenou vodu','Kouř z lektvarů'),
      Q('Jak se trojice v prvním ročníku dostala z Ďáblova osidla?','Hermiona použila oheň','Harry ho přesekl mečem','Ron použil Expelliarmus','Neville přinesl mandragoru'),
      Q('Proč byla u Bradavic vysazena Vrba mlátička?','Aby ukryla cestu, kterou Lupin používal při proměnách','Aby chránila vstup do Tajemné komnaty','Aby hlídala skleníky','Jako památka na zakladatele školy'),
      Q('Co umožní žaberník člověku pod vodou?','Dýchat pod vodou','Být neviditelný','Mluvit s rybami','Proměnit se v žraloka'),
      Q('Jak se jmenuje rostlina, kterou Neville přivezl do školy v pátém ročníku?','Mimbulus mimbletonia','Ďáblovo osidlo','Vrba mlátička','Přelivník'),
      Q('Co Mimbulus mimbletonia vystřikuje při obraně?','Smradlavou mízu','Jedovaté trny','Oheň','Spory uspávajícího prášku'),
      Q('K čemu se používá hnis z bubotuber?','K léčbě akné','K vaření Felix Felicis','K odpuzování mozkomorů','K čištění hůlek'),
      Q('Čím je nebezpečná Jedovatá tentakule?','Může chňapat a kousat','Křikem zabíjí','Mění lidi v kámen','Vylučuje baziliščí jed'),
      Q('Kdo v knižní verzi přinesl Harrymu žaberník před druhým úkolem Turnaje tří kouzelníků?','Dobby','Neville Longbottom','Cedric Diggory','Hermiona Grangerová'),
      Q('Co chránilo jednu z překážek na cestě ke Kameni mudrců pod padacími dveřmi?','Ďáblovo osidlo','Mandragory','Vrba mlátička','Mimbulus mimbletonia'),
      Q('Který student je během školních let mimořádně nadaný na bylinkářství?','Neville Longbottom','Draco Malfoy','Seamus Finnigan','Dean Thomas'),
      Q('K čemu se používá dittany?','K ošetření a zacelení ran','K vyvolání věšteckého snu','K proměně vlasů','K uspání draka'),
      Q('Jak reaguje Vrba mlátička na někoho, kdo se přiblíží příliš blízko?','Útočí svými větvemi','Začne křičet','Zmizí','Otevře tajné dveře sama od sebe'),
      Q('Ve které části školy probíhá většina hodin bylinkářství?','Ve sklenících','V žalářích','V Astronomické věži','Ve Velké síni')
    ]},
    astronomy:{title:'Astronomie',questions:[
      Q('Kdo vyučuje astronomii během Harryho studia?','Profesorka Sinistrová','Profesorka Trelawneyová','Profesorka Vectorová','Madame Hoochová'),
      Q('Kdy se v Bradavicích běžně konají hodiny astronomie?','V noci','Každé ráno před snídaní','Pouze o víkendech','V poledne'),
      Q('Kde studenti astronomie pozorují oblohu?','Z Astronomické věže','Z Velké síně','Ze skleníků','Z kuchyně'),
      Q('Co se studenti v astronomii učí sledovat?','Hvězdy a pohyby planet','Pouze znamení ve snech','Přísady do lektvarů','Rodokmeny kouzelníků'),
      Q('Kdy probíhala Harryho praktická zkouška NKÚ z astronomie?','V noci','Za svítání','V poledne','Odpoledne po famfrpálu'),
      Q('Jakou událost Harry během praktického NKÚ z astronomie zahlédl?','Pokus Umbridgeové a ministerských kouzelníků odvést Hagrida','Útěk Siriuse z Bradavic','Přílet Beauxbatons','Zápas ve famfrpálu'),
      Q('Kdo byl zasažen omračovacími kouzly, když se během této události snažil Hagridovi pomoci?','Minerva McGonagallová','Filius Kratiknot','Severus Snape','Pomona Prýtová'),
      Q('Na které věži došlo na konci šestého ročníku ke smrti Albuse Brumbála?','Na Astronomické věži','Na Severní věži','Na věži Nebelvíru','Na sovinci'),
      Q('Které jméno postavy je zároveň názvem nejjasnější hvězdy noční oblohy?','Sirius','Remus','Severus','Rubeus'),
      Q('Které jméno člena rodu Blacků je zároveň názvem hvězdy v souhvězdí Lva?','Regulus','Draco','Orion','Lucius'),
      Q('Které jméno Smrtijedky je zároveň názvem jasné hvězdy v Orionu?','Bellatrix','Narcissa','Alecto','Millicent'),
      Q('Která postava nese jméno stejné jako souhvězdí?','Andromeda Tonksová','Molly Weasleyová','Lily Potterová','Petunie Dursleyová'),
      Q('Která postava nese jméno podle souhvězdí Draka?','Draco Malfoy','Dean Thomas','Dudley Dursley','Dennis Creevey'),
      Q('Která planeta je známá Velkou rudou skvrnou?','Jupiter','Mars','Venuše','Merkur'),
      Q('Která planeta je označována jako rudá planeta?','Mars','Jupiter','Saturn','Neptun'),
      Q('Která planeta je největší ve Sluneční soustavě?','Jupiter','Saturn','Země','Mars'),
      Q('Která planeta je nejblíže Slunci?','Merkur','Venuše','Země','Mars'),
      Q('Jak se jmenuje přirozená družice Země?','Měsíc','Europa','Titan','Io'),
      Q('Která planeta je proslulá výraznou soustavou prstenců?','Saturn','Merkur','Mars','Venuše'),
      Q('Co studenti při praktickém pozorování oblohy používají?','Dalekohledy','Křišťálové koule','Míchací hůlky','Košťata')
    ]}
  };
  window.BradaviceQuizBanks=banks;
})();
